
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Reproduce "experiment report" baselines in a *fully traceable* way.

This script is designed for two use-cases:

(1) EXACT reproducibility against the provided artifact bundle (实验结果.zip)
    - Extracts: split patient-IDs, selected feature names, best hyper-parameters
    - Re-trains models on your local clinical_csv + radiomics_csv
    - Evaluates Harrell's C-index and bootstrapped mean±std / CI

(2) SCRATCH mode (no artifacts)
    - Builds a report-like pipeline: impute -> one-hot -> min-max -> mRMR -> fit -> test C-index

Why this script:
- Your current runs used (a) different splits, (b) different clinical coding, (c) different K for mRMR.
- The artifacts show the report used one-hot on integer-coded clinical categories (e.g. Overall.Stage_3, Histology_4),
  and selected ~1% of radiomics features (≈16-17), not K=50.

Author: (generated by ChatGPT)
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import zipfile
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import yaml
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.model_selection import KFold
from sklearn.feature_selection import mutual_info_classif, mutual_info_regression


# -----------------------------
# Metrics
# -----------------------------

def harrell_c_index(event: np.ndarray, time: np.ndarray, risk: np.ndarray) -> float:
    """
    Harrell's C-index for right-censored survival.

    event: boolean (True if event observed)
    time: survival/censor time
    risk: higher means higher hazard (shorter survival)

    Comparable pairs: (i,j) where time_i < time_j and event_i == True.
    Concordant if risk_i > risk_j, ties contribute 0.5.
    """
    event = event.astype(bool)
    time = time.astype(float)
    risk = risk.astype(float)

    n = len(time)
    concordant = 0.0
    discordant = 0.0
    tied_risk = 0.0
    comparable = 0.0

    for i in range(n):
        if not event[i]:
            continue
        ti = time[i]
        ri = risk[i]
        # only compare to those with longer time
        for j in range(n):
            if ti < time[j]:
                comparable += 1.0
                rj = risk[j]
                if ri > rj:
                    concordant += 1.0
                elif ri < rj:
                    discordant += 1.0
                else:
                    tied_risk += 1.0

    if comparable == 0:
        return float("nan")
    return float((concordant + 0.5 * tied_risk) / comparable)


def bootstrap_cindex(
    df: pd.DataFrame,
    risk_col: str,
    time_col: str,
    event_col: str,
    n_boot: int = 200,
    seed: int = 0,
) -> Dict[str, float]:
    """
    Bootstrap resampling on rows; return mean/std and two CIs:
      - percentile CI
      - normal-approx CI (mean ± 1.96*std)  (often what "report" tables implicitly use)
    """
    rng = np.random.default_rng(seed)
    event = df[event_col].astype(bool).to_numpy()
    time = df[time_col].astype(float).to_numpy()
    risk = df[risk_col].astype(float).to_numpy()
    n = len(df)

    vals = []
    for _ in range(n_boot):
        idx = rng.integers(0, n, n)
        vals.append(harrell_c_index(event[idx], time[idx], risk[idx]))
    vals = np.asarray(vals, dtype=float)

    mean = float(np.nanmean(vals))
    std = float(np.nanstd(vals, ddof=1))
    p025, p975 = np.nanpercentile(vals, [2.5, 97.5])

    z = 1.96
    ci_norm_lo = mean - z * std
    ci_norm_hi = mean + z * std

    return {
        "boot_mean": mean,
        "boot_std": std,
        "ci_pct_2.5": float(p025),
        "ci_pct_97.5": float(p975),
        "ci_norm_2.5": float(ci_norm_lo),
        "ci_norm_97.5": float(ci_norm_hi),
    }


# -----------------------------
# Clinical preprocessing (REPORT-LIKE)
# -----------------------------

_STAGE_MAP = {"I": 0, "II": 1, "IIIa": 2, "IIIb": 3}
_HISTO_MAP = {
    "adenocarcinoma": 0,
    "large cell": 1,
    "nos": 2,
    "squamous cell carcinoma": 3,
}

def _canon_str(x) -> str:
    if pd.isna(x):
        return ""
    return str(x).strip().lower()

def encode_clinical_report_like(df: pd.DataFrame) -> pd.DataFrame:
    """
    Convert raw Lung1 clinical columns into the integer-coded categories
    that match the artifact feature names:
      gender -> 0/1
      Overall.Stage -> 0..3
      Histology -> 0..4 (4=unknown/missing)
      clinical.T.Stage -> 0..5 (0=missing)
      Clinical.N.Stage -> 0..4 (missing -> 5 if needed)
      Clinical.M.Stage -> 0..2   (map 3 -> 2; missing -> 3 if needed)
    and keep age as numeric.
    """
    out = pd.DataFrame(index=df.index)

    # age (numeric)
    out["age"] = pd.to_numeric(df["age"], errors="coerce")

    # gender: female/male -> 0/1
    g = df["gender"].map(lambda x: _canon_str(x))
    # if future unknowns appear, map to 2
    out["gender"] = g.map({"female": 0, "male": 1}).fillna(2).astype(int)

    # Overall.Stage: I/II/IIIa/IIIb -> 0..3 ; missing/other -> 4
    st = df["Overall.Stage"].map(lambda x: str(x).strip() if not pd.isna(x) else "")
    out["Overall.Stage"] = st.map(_STAGE_MAP).fillna(4).astype(int)

    # Histology: map 4 strings -> 0..3 ; missing/other -> 4
    h = df["Histology"].map(lambda x: _canon_str(x))
    out["Histology"] = h.map(_HISTO_MAP).fillna(4).astype(int)

    # T stage: numeric 1..5; missing -> 0
    t = pd.to_numeric(df["clinical.T.Stage"], errors="coerce")
    out["clinical.T.Stage"] = t.fillna(0).astype(int)

    # N stage: numeric 0..4; missing -> 5
    n = pd.to_numeric(df["Clinical.N.Stage"], errors="coerce")
    out["Clinical.N.Stage"] = n.fillna(5).astype(int)

    # M stage: values 0,1,3; map 3 -> 2 ; missing -> 3
    m = pd.to_numeric(df["Clinical.M.Stage"], errors="coerce")
    m = m.map(lambda x: 2 if x == 3 else x)
    out["Clinical.M.Stage"] = m.fillna(3).astype(int)

    return out


def build_clinical_matrix(
    clin_raw: pd.DataFrame,
    train_ids: List[str],
    use_age: int = 1,
    use_gender: int = 1,
    use_histology: int = 1,
    use_t_stage: int = 1,
    use_n_stage: int = 1,
    use_m_stage: int = 1,
    use_stage: int = 1,
    age_impute: str = "mean",
    scale_numeric: bool = True,
) -> Tuple[pd.DataFrame, Dict[str, object]]:
    """
    Build report-like clinical design matrix:
      - integer coding (to match e.g. Histology_4, Overall.Stage_3)
      - one-hot for categorical
      - min-max for age (numeric)

    Returns:
      X_clin (DataFrame with stable column names)
      fitted objects dict
    """
    coded = encode_clinical_report_like(clin_raw)

    # choose columns
    num_cols = []
    cat_cols = []
    if use_age:
        num_cols.append("age")
    if use_gender:
        cat_cols.append("gender")
    if use_histology:
        cat_cols.append("Histology")
    if use_t_stage:
        cat_cols.append("clinical.T.Stage")
    if use_n_stage:
        cat_cols.append("Clinical.N.Stage")
    if use_m_stage:
        cat_cols.append("Clinical.M.Stage")
    if use_stage:
        cat_cols.append("Overall.Stage")

    # Impute numeric
    fitted: Dict[str, object] = {}
    X_num = pd.DataFrame(index=coded.index)
    if num_cols:
        imp = SimpleImputer(strategy=age_impute)
        imp.fit(coded.loc[train_ids, num_cols])
        X_num[num_cols] = imp.transform(coded[num_cols])
        fitted["num_imputer"] = imp

        if scale_numeric:
            scaler = MinMaxScaler()
            scaler.fit(X_num.loc[train_ids, num_cols])
            X_num[num_cols] = scaler.transform(X_num[num_cols])
            fitted["num_scaler"] = scaler

    # One-hot categorical with fixed category sets to ensure feature-name match
    X_cat = pd.DataFrame(index=coded.index)
    if cat_cols:
        categories = []
        for c in cat_cols:
            if c == "gender":
                categories.append([0, 1, 2])
            elif c == "Histology":
                categories.append([0, 1, 2, 3, 4])
            elif c == "Overall.Stage":
                categories.append([0, 1, 2, 3, 4])
            elif c == "clinical.T.Stage":
                categories.append([0, 1, 2, 3, 4, 5])
            elif c == "Clinical.N.Stage":
                categories.append([0, 1, 2, 3, 4, 5])
            elif c == "Clinical.M.Stage":
                categories.append([0, 1, 2, 3])
            else:
                # fallback: infer
                categories.append(sorted(coded[c].dropna().unique().tolist()))

        try:
            ohe = OneHotEncoder(categories=categories, sparse_output=False, handle_unknown="ignore")
        except TypeError:
            ohe = OneHotEncoder(categories=categories, sparse=False, handle_unknown="ignore")
        ohe.fit(coded.loc[train_ids, cat_cols])

        arr = ohe.transform(coded[cat_cols])
        feat_names = list(ohe.get_feature_names_out(cat_cols))
        X_cat = pd.DataFrame(arr, columns=feat_names, index=coded.index)
        fitted["ohe"] = ohe

    X = pd.concat([X_num, X_cat], axis=1)
    return X, fitted


# -----------------------------
# Radiomics preprocessing
# -----------------------------

def load_radiomics_csv(path: str, id_col: str = "PatientID") -> pd.DataFrame:
    df = pd.read_csv(path)
    if id_col not in df.columns:
        raise ValueError(f"[radiomics] id_col='{id_col}' not found. available: {df.columns.tolist()[:20]} ...")
    df[id_col] = df[id_col].astype(str)
    df = df.set_index(id_col)

    # drop non-numeric columns (if any)
    keep_cols = []
    for c in df.columns:
        if pd.api.types.is_numeric_dtype(df[c]):
            keep_cols.append(c)
        else:
            # try coerce
            coerced = pd.to_numeric(df[c], errors="coerce")
            if coerced.notna().sum() > 0:
                df[c] = coerced
                keep_cols.append(c)
    df = df[keep_cols]
    return df


def preprocess_radiomics(
    rad: pd.DataFrame,
    train_ids: List[str],
    scale: str = "minmax",
    impute: str = "mean",
) -> Tuple[pd.DataFrame, Dict[str, object]]:
    fitted: Dict[str, object] = {}

    # impute
    imp = SimpleImputer(strategy=impute)
    imp.fit(rad.loc[train_ids])
    X = pd.DataFrame(imp.transform(rad), columns=rad.columns, index=rad.index)
    fitted["imputer"] = imp

    # scale
    if scale == "minmax":
        scaler = MinMaxScaler()
        scaler.fit(X.loc[train_ids])
        X = pd.DataFrame(scaler.transform(X), columns=X.columns, index=X.index)
        fitted["scaler"] = scaler
    elif scale == "none":
        pass
    else:
        raise ValueError(f"Unsupported radiomics scale: {scale}")

    return X, fitted


# -----------------------------
# Feature selection (scratch mode)
# -----------------------------

def mrmr_select(
    X: pd.DataFrame,
    time: np.ndarray,
    event: np.ndarray,
    k: int,
    seed: int = 0,
    relevance: str = "event+time",
    redundancy: str = "corr",
) -> List[str]:
    """
    A practical mRMR approximation for survival:
      relevance:
        - "event": MI(feature, event)
        - "time":  MI(feature, log1p(time))
        - "event+time": sum of both
      redundancy:
        - "corr": mean absolute Pearson corr with selected features

    NOTE: This may not match a specific external mRMR library exactly,
    but it is stable and easy to audit.
    """
    rng = np.random.default_rng(seed)
    cols = list(X.columns)
    Xv = X.to_numpy(dtype=float)

    # relevance
    rel = np.zeros(Xv.shape[1], dtype=float)
    if relevance in ("event", "event+time"):
        rel += mutual_info_classif(Xv, event.astype(int), random_state=seed, discrete_features=False)
    if relevance in ("time", "event+time"):
        rel += mutual_info_regression(Xv, np.log1p(time.astype(float)), random_state=seed)

    # start: best relevance
    selected = []
    remaining = list(range(Xv.shape[1]))
    first = int(np.nanargmax(rel))
    selected.append(first)
    remaining.remove(first)

    # precompute corr matrix progressively (cheap enough for k<=100)
    for _ in range(1, k):
        best_idx = None
        best_score = -np.inf
        for j in remaining:
            if redundancy == "corr" and len(selected) > 0:
                # mean abs corr with selected
                r = []
                xj = Xv[:, j]
                for s in selected:
                    xs = Xv[:, s]
                    # safe corr
                    if np.std(xj) < 1e-12 or np.std(xs) < 1e-12:
                        r.append(0.0)
                    else:
                        r.append(abs(np.corrcoef(xj, xs)[0, 1]))
                red = float(np.mean(r)) if r else 0.0
            else:
                red = 0.0
            score = rel[j] - red
            # tie-breaker by tiny noise for determinism
            score += 1e-12 * rng.normal()
            if score > best_score:
                best_score = score
                best_idx = j
        selected.append(best_idx)
        remaining.remove(best_idx)

    return [cols[i] for i in selected]


# -----------------------------
# Models
# -----------------------------

def fit_predict_cph(
    X_train: pd.DataFrame,
    X_test: pd.DataFrame,
    time_train: np.ndarray,
    event_train: np.ndarray,
    time_test: np.ndarray,
    event_test: np.ndarray,
    alpha: float = 0.0,
    ties: str = "efron",
    n_iter: Optional[int] = None,
) -> Tuple[np.ndarray, np.ndarray]:
    """
    CoxPH with ties=efron if lifelines is installed; else fallback to sksurv CoxPHSurvivalAnalysis (ties may differ).
    Returns (risk_train, risk_test).
    """
    # Prefer lifelines because the artifact best_params includes "ties: efron".
    try:
        from lifelines import CoxPHFitter
    except Exception:
        CoxPHFitter = None

    if CoxPHFitter is not None:
        df_tr = X_train.copy()
        df_tr["time"] = time_train
        df_tr["event"] = event_train.astype(int)
        cph = CoxPHFitter(penalizer=float(alpha))
        fit_opts = {}
        if n_iter is not None:
            fit_opts['max_steps'] = int(n_iter)
        cph.fit(df_tr, duration_col='time', event_col='event', show_progress=False, fit_options=(fit_opts or None))

        risk_tr = cph.predict_partial_hazard(X_train).to_numpy().reshape(-1)
        risk_te = cph.predict_partial_hazard(X_test).to_numpy().reshape(-1)
        return risk_tr, risk_te

    # fallback: sksurv
    try:
        from sksurv.linear_model import CoxPHSurvivalAnalysis
        from sksurv.util import Surv
    except Exception as e:
        raise RuntimeError(
            "Neither lifelines nor scikit-survival is available. "
            "Install one of them. For best match with report, install lifelines."
        ) from e

    y_train = Surv.from_arrays(event_train.astype(bool), time_train.astype(float))
    model = CoxPHSurvivalAnalysis(alpha=float(alpha))
    model.fit(X_train.to_numpy(), y_train)
    risk_tr = model.predict(X_train.to_numpy()).reshape(-1)
    risk_te = model.predict(X_test.to_numpy()).reshape(-1)
    return risk_tr, risk_te


def fit_predict_coxnet_cv(
    X_train: pd.DataFrame,
    X_test: pd.DataFrame,
    time_train: np.ndarray,
    event_train: np.ndarray,
    seed: int,
    l1_ratio: float = 0.001,
    n_alphas: int = 20,
    n_folds: int = 5,
) -> Tuple[np.ndarray, np.ndarray, Dict[str, float]]:
    """
    CoxNet (elastic-net) with CV selection of alpha by mean Harrell C-index across folds.

    Returns:
      risk_train (using best alpha, refit on full train)
      risk_test
      info dict: best_alpha, best_cv_cindex
    """
    try:
        from sksurv.linear_model import CoxnetSurvivalAnalysis
        from sksurv.util import Surv
    except Exception as e:
        raise RuntimeError("scikit-survival is required for CoxNet reproduction.") from e

    Xtr = X_train.to_numpy(dtype=float)
    Xte = X_test.to_numpy(dtype=float)
    y = Surv.from_arrays(event_train.astype(bool), time_train.astype(float))

    # Fit once to get alpha path
    base = CoxnetSurvivalAnalysis(
    l1_ratio=float(l1_ratio),
    n_alphas=int(n_alphas),
    alpha_min_ratio=1e-4,)
    base.fit(Xtr, y)

    # The library stores alphas_ after fit
    alphas = getattr(base, "alphas_", None)
    if alphas is None:
        # fall back to user-provided alphas if needed
        raise RuntimeError("CoxnetSurvivalAnalysis did not expose alphas_. Please check scikit-survival version.")

    kf = KFold(n_splits=int(n_folds), shuffle=True, random_state=int(seed))
    cv_scores = np.zeros_like(alphas, dtype=float)
    cv_counts = np.zeros_like(alphas, dtype=float)

    for tr_idx, va_idx in kf.split(Xtr):
        X_tr, X_va = Xtr[tr_idx], Xtr[va_idx]
        y_tr = Surv.from_arrays(event_train[tr_idx].astype(bool), time_train[tr_idx].astype(float))

        m = CoxnetSurvivalAnalysis(l1_ratio=float(l1_ratio), alphas=alphas)
        m.fit(X_tr, y_tr)

        # predict may return (n_samples, n_alphas) or (n_samples,) depending on version
        pred = m.predict(X_va)
        if pred.ndim == 1:
            pred = pred.reshape(-1, 1)

        # compute c-index for each alpha
        ev_va = event_train[va_idx].astype(bool)
        tm_va = time_train[va_idx].astype(float)
        for j in range(pred.shape[1]):
            c = harrell_c_index(ev_va, tm_va, pred[:, j])
            if not np.isnan(c):
                cv_scores[j] += c
                cv_counts[j] += 1

    mean_cv = np.divide(cv_scores, np.maximum(cv_counts, 1.0))
    best_j = int(np.nanargmax(mean_cv))
    best_alpha = float(alphas[best_j])
    best_cv = float(mean_cv[best_j])

    # Refit final model on full train using only best alpha
    final = CoxnetSurvivalAnalysis(l1_ratio=float(l1_ratio), alphas=[best_alpha])
    final.fit(Xtr, ytr)
    if np.all(final.coef_ == 0):
        # fallback to smallest alpha
        best_alpha = float(np.min(alphas))
        final = CoxnetSurvivalAnalysis(l1_ratio=float(l1_ratio), alphas=[best_alpha])
        final.fit(Xtr, ytr)
    risk_tr = final.predict(Xtr).reshape(-1)
    risk_te = final.predict(Xte).reshape(-1)

    return risk_tr, risk_te, {"best_alpha": best_alpha, "best_cv_cindex": best_cv}


def fit_predict_gbsa(
    X_train: pd.DataFrame,
    X_test: pd.DataFrame,
    time_train: np.ndarray,
    event_train: np.ndarray,
    params: Dict[str, object],
) -> Tuple[np.ndarray, np.ndarray]:
    """
    GradientBoostingSurvivalAnalysis (scikit-survival).
    Params should include keys like in best_params_*.yaml from artifacts.
    """
    try:
        from sksurv.ensemble import GradientBoostingSurvivalAnalysis
        from sksurv.util import Surv
    except Exception as e:
        raise RuntimeError("scikit-survival is required for GBSA reproduction.") from e

    # Filter only valid GBSA params (robust to extras)
    valid = {
        "loss", "learning_rate", "n_estimators", "subsample",
        "criterion", "dropout_rate", "max_depth", "max_leaf_nodes",
        "max_features", "min_samples_split", "min_samples_leaf",
        "min_weight_fraction_leaf", "min_impurity_decrease",
        "random_state"
    }
    gb_params = {k: params[k] for k in params.keys() if k in valid}

    # Ensure correct types
    if "random_state" not in gb_params:
        gb_params["random_state"] = 0

    model = GradientBoostingSurvivalAnalysis(**gb_params)
    y_train = Surv.from_arrays(event_train.astype(bool), time_train.astype(float))

    model.fit(X_train.to_numpy(dtype=float), y_train)
    risk_tr = model.predict(X_train.to_numpy(dtype=float)).reshape(-1)
    risk_te = model.predict(X_test.to_numpy(dtype=float)).reshape(-1)
    return risk_tr, risk_te


# -----------------------------
# Artifact recipe extraction
# -----------------------------

@dataclass
class RecipeEntry:
    task: str               # Radiomics / Clinic / Clinic+Radiomics
    model: str              # cph / coxnet / gbsa
    seed_dir: str           # seed_9 etc (as in artifacts)
    train_ids: List[str]
    test_ids: List[str]
    selected_features: List[str]  # typically "secondary_selected_features"
    best_params: Dict[str, object]


def _detect_model_dir_name(d: str) -> Optional[str]:
    base = os.path.basename(d)
    if base == "CoxPHSurvivalAnalysis":
        return "cph"
    if base == "CoxnetSurvivalAnalysis":
        return "coxnet"
    if base == "GradientBoostingSurvivalAnalysis":
        return "gbsa"
    return None


def extract_recipe(report_zip: str, out_dir: str) -> str:
    os.makedirs(out_dir, exist_ok=True)
    unpack_dir = os.path.join(out_dir, "unpacked")
    os.makedirs(unpack_dir, exist_ok=True)

    with zipfile.ZipFile(report_zip, "r") as zf:
        zf.extractall(unpack_dir)

    tasks = ["Radiomics", "Clinic", "Clinic+Radiomics"]
    recipe: List[RecipeEntry] = []

    for task in tasks:
        task_dir = os.path.join(unpack_dir, task)
        if not os.path.isdir(task_dir):
            continue
        seed_dirs = sorted([d for d in os.listdir(task_dir) if d.startswith("seed_")])
        for sd in seed_dirs:
            sd_path = os.path.join(task_dir, sd)
            if not os.path.isdir(sd_path):
                continue
            # each seed dir has one model dir
            model_dirs = [os.path.join(sd_path, x) for x in os.listdir(sd_path) if os.path.isdir(os.path.join(sd_path, x))]
            for md in model_dirs:
                model_short = _detect_model_dir_name(md)
                if model_short is None:
                    continue

                # train/test preds -> split IDs
                train_pred = None
                test_pred = None
                for fn in os.listdir(md):
                    if re.match(r"train_preds_.*\.xlsx$", fn):
                        train_pred = os.path.join(md, fn)
                    elif re.match(r"test_preds_.*\.xlsx$", fn):
                        test_pred = os.path.join(md, fn)

                if train_pred is None or test_pred is None:
                    # Some folders might not store preds; skip
                    continue

                df_tr = pd.read_excel(train_pred)
                df_te = pd.read_excel(test_pred)
                train_ids = df_tr["pid"].astype(str).tolist()
                test_ids = df_te["pid"].astype(str).tolist()

                # selected features
                sel_path = None
                for fn in os.listdir(md):
                    if re.match(r"selected_features_.*\.xlsx$", fn):
                        sel_path = os.path.join(md, fn)
                        break
                selected = []
                if sel_path is not None:
                    sel = pd.read_excel(sel_path)
                    col = "secondary_selected_features" if "secondary_selected_features" in sel.columns else sel.columns[0]
                    selected = sel[col].dropna().astype(str).tolist()
                    # drop blanks
                    selected = [s for s in selected if str(s).strip() != ""]

                # best params
                params_path = None
                for fn in os.listdir(md):
                    if re.match(r"best_params_.*\.ya?ml$", fn):
                        params_path = os.path.join(md, fn)
                        break
                best_params: Dict[str, object] = {}
                if params_path is not None:
                    with open(params_path, "r", encoding="utf-8") as f:
                        best_params = yaml.safe_load(f) or {}

                recipe.append(
                    RecipeEntry(
                        task=task,
                        model=model_short,
                        seed_dir=sd,
                        train_ids=train_ids,
                        test_ids=test_ids,
                        selected_features=selected,
                        best_params=best_params,
                    )
                )

    # save JSON
    recipe_json_path = os.path.join(out_dir, "report_recipe.json")
    out = []
    for r in recipe:
        out.append({
            "task": r.task,
            "model": r.model,
            "seed_dir": r.seed_dir,
            "train_ids": r.train_ids,
            "test_ids": r.test_ids,
            "selected_features": r.selected_features,
            "best_params": r.best_params,
        })
    with open(recipe_json_path, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)

    return recipe_json_path


def load_recipe(recipe_json: str) -> List[RecipeEntry]:
    with open(recipe_json, "r", encoding="utf-8") as f:
        data = json.load(f)
    out = []
    for d in data:
        out.append(RecipeEntry(
            task=d["task"],
            model=d["model"],
            seed_dir=d["seed_dir"],
            train_ids=list(d["train_ids"]),
            test_ids=list(d["test_ids"]),
            selected_features=list(d.get("selected_features", [])),
            best_params=dict(d.get("best_params", {})),
        ))
    return out


def pick_recipe_entry(recipe: List[RecipeEntry], task: str, model: str) -> RecipeEntry:
    cand = [r for r in recipe if r.task.lower() == task.lower() and r.model == model]
    if len(cand) == 0:
        raise ValueError(f"No entry found for task={task} model={model}. Available: {sorted(set((r.task,r.model) for r in recipe))}")
    # if multiple, pick the first (should not happen)
    return cand[0]


# -----------------------------
# Run experiments
# -----------------------------

def load_clinical_csv(path: str, id_col: str = "PatientID") -> pd.DataFrame:
    df = pd.read_csv(path)
    if id_col not in df.columns:
        raise ValueError(f"[clinical] id_col='{id_col}' not found. available: {df.columns.tolist()[:20]} ...")
    df[id_col] = df[id_col].astype(str)
    df = df.set_index(id_col)
    return df


def build_xy_from_raw(
    clinical_csv: str,
    radiomics_csv: str,
    clinical_id_col: str,
    radiomics_id_col: str,
    time_col: str,
    event_col: str,
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.Series, pd.Series]:
    clin = load_clinical_csv(clinical_csv, id_col=clinical_id_col)
    rad = load_radiomics_csv(radiomics_csv, id_col=radiomics_id_col)

    # intersection on patient IDs
    common = clin.index.intersection(rad.index)
    clin = clin.loc[common].copy()
    rad = rad.loc[common].copy()

    # labels from clinical
    time = pd.to_numeric(clin[time_col], errors="coerce")
    event = pd.to_numeric(clin[event_col], errors="coerce").fillna(0).astype(int)

    # Remove rows with missing time
    keep = time.notna()
    clin = clin.loc[keep]
    rad = rad.loc[keep]
    time = time.loc[keep]
    event = event.loc[keep]

    return clin, rad, time, event


def ensure_ids_exist(ids: List[str], index: pd.Index, name: str) -> List[str]:
    idx_set = set(index.astype(str).tolist())
    miss = [i for i in ids if i not in idx_set]
    if miss:
        print(f"[WARN] {name}: {len(miss)} ids not found in your dataset. First few: {miss[:10]}", file=sys.stderr)
    return [i for i in ids if i in idx_set]



def load_split_json(path: str) -> Tuple[List[str], List[str]]:
    """
    Load a custom split json. Supported formats:
      - {'train_ids': [...], 'val_ids': [...], 'test_ids': [...]}
      - {'train': [...], 'val': [...], 'test': [...]}
    Training will use (train_ids + val_ids) if val exists.
    """
    with open(path, 'r', encoding='utf-8') as f:
        d = json.load(f)
    train_ids = d.get('train_ids', d.get('train', []))
    val_ids = d.get('val_ids', d.get('val', []))
    test_ids = d.get('test_ids', d.get('test', []))
    train_ids = [str(x) for x in train_ids] if train_ids is not None else []
    val_ids = [str(x) for x in val_ids] if val_ids is not None else []
    test_ids = [str(x) for x in test_ids] if test_ids is not None else []
    train_all = train_ids + val_ids
    if not train_all:
        raise ValueError(f"split_json has empty train (and val) ids: {path}")
    if not test_ids:
        raise ValueError(f"split_json has empty test ids: {path}")
    return train_all, test_ids

def run_one(
    task: str,
    model: str,
    clin_raw: pd.DataFrame,
    rad_raw: pd.DataFrame,
    time: pd.Series,
    event: pd.Series,
    train_ids: List[str],
    test_ids: List[str],
    selected_features: Optional[List[str]],
    best_params: Dict[str, object],
    seed: int,
    mode: str,
    mrmr_ratio: float,
    mrmr_k: Optional[int],
    bootstrap: int,
    out_dir: str,
    clinical_flags: Dict[str, int],
    age_impute: str,
) -> Dict[str, object]:
    """
    mode:
      - exact: use selected_features from artifacts
      - scratch: compute mRMR on train (radiomics only) then optionally fuse
    """
    os.makedirs(out_dir, exist_ok=True)

    # ensure ids exist after intersection
    train_ids = ensure_ids_exist(train_ids, clin_raw.index, "train_ids")
    test_ids = ensure_ids_exist(test_ids, clin_raw.index, "test_ids")

    y_time = time.astype(float)
    y_event = event.astype(int)

    # build clinical matrix (always build "full" to allow selecting artifact one-hot columns)
    X_clin, _ = build_clinical_matrix(
        clin_raw,
        train_ids=train_ids,
        age_impute=age_impute,
        use_age=clinical_flags["use_age"],
        use_gender=clinical_flags["use_gender"],
        use_histology=clinical_flags["use_histology"],
        use_t_stage=clinical_flags["use_t_stage"],
        use_n_stage=clinical_flags["use_n_stage"],
        use_m_stage=clinical_flags["use_m_stage"],
        use_stage=clinical_flags["use_stage"],
        scale_numeric=True,
    )

    # radiomics preprocess
    X_rad, _ = preprocess_radiomics(rad_raw, train_ids=train_ids, scale="minmax", impute="mean")

    if task.lower() == "radiomics":
        X_all = X_rad
    elif task.lower() == "clinic":
        X_all = X_clin
    elif task.lower() in ("clinic+radiomics", "fusion"):
        X_all = pd.concat([X_rad, X_clin], axis=1)
    else:
        raise ValueError(f"Unknown task: {task}")

    # feature selection
    if mode == "exact":
        if not selected_features:
            raise ValueError("EXACT mode requires selected_features from recipe/artifacts.")
        # select subset
        missing = [f for f in selected_features if f not in X_all.columns]
        if missing:
            raise ValueError(
                f"Some selected features are missing from your constructed matrix (n={len(missing)}). "
                f"First few: {missing[:10]}\n"
                f"Tip: this usually means your clinical one-hot coding does NOT match the report."
            )
        X_use = X_all[selected_features].copy()
        selected = selected_features
    elif mode == "scratch":
        # mRMR only on radiomics (report style); then build task matrix
        # Decide K
        if mrmr_k is not None:
            k = int(mrmr_k)
        else:
            k = int(np.ceil(X_rad.shape[1] * float(mrmr_ratio)))
        k = max(1, min(k, X_rad.shape[1]))
        sel = mrmr_select(
            X=X_rad.loc[train_ids],
            time=y_time.loc[train_ids].to_numpy(),
            event=y_event.loc[train_ids].to_numpy(),
            k=k,
            seed=seed,
            relevance="event+time",
            redundancy="corr",
        )
        if task.lower() == "radiomics":
            X_use = X_rad[sel].copy()
        elif task.lower() == "clinic":
            X_use = X_clin.copy()
        else:
            X_use = pd.concat([X_rad[sel], X_clin], axis=1).copy()
        selected = list(X_use.columns)
    else:
        raise ValueError(f"Unknown mode: {mode}")

    # split matrices
    X_train = X_use.loc[train_ids]
    X_test = X_use.loc[test_ids]
    t_train = y_time.loc[train_ids].to_numpy()
    e_train = y_event.loc[train_ids].to_numpy().astype(bool)
    t_test = y_time.loc[test_ids].to_numpy()
    e_test = y_event.loc[test_ids].to_numpy().astype(bool)

    # fit model
    if model == "cph":
        alpha = float(best_params.get("alpha", 0.0))
        ties = str(best_params.get("ties", "efron"))
        n_iter = best_params.get('n_iter', None)
        risk_tr, risk_te = fit_predict_cph(X_train, X_test, t_train, e_train, t_test, e_test, alpha=alpha, ties=ties, n_iter=n_iter)
        extra = {'alpha': alpha, 'ties': ties, 'n_iter': n_iter}
    elif model == "coxnet":
        l1_ratio = float(best_params.get("l1_ratio", 0.001))
        n_alphas = int(best_params.get("n_alphas", 20))
        risk_tr, risk_te, info = fit_predict_coxnet_cv(
            X_train, X_test, t_train, e_train, seed=seed, l1_ratio=l1_ratio, n_alphas=n_alphas, n_folds=5
        )
        extra = {"l1_ratio": l1_ratio, "n_alphas": n_alphas, **info}
    elif model == "gbsa":
        risk_tr, risk_te = fit_predict_gbsa(X_train, X_test, t_train, e_train, best_params)
        extra = dict(best_params)
    else:
        raise ValueError(f"Unknown model: {model}")

    # scores
    train_ci = harrell_c_index(e_train, t_train, risk_tr)
    test_ci = harrell_c_index(e_test, t_test, risk_te)

    df_test = pd.DataFrame({
        "pid": test_ids,
        "time": t_test,
        "event": e_test.astype(int),
        "pred_risk": risk_te,
    })
    boot = bootstrap_cindex(df_test, risk_col="pred_risk", time_col="time", event_col="event", n_boot=bootstrap, seed=seed)

    out = {
        "task": task,
        "model": model,
        "mode": mode,
        "n_train": int(len(train_ids)),
        "n_test": int(len(test_ids)),
        "n_features": int(X_use.shape[1]),
        "train_cindex": float(train_ci),
        "test_cindex": float(test_ci),
        **boot,
        "selected_features": selected,
        "model_params": extra,
    }

    # save artifacts
    out_path = os.path.join(out_dir, f"result_{task.replace('+','_')}_{model}_{mode}.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)

    pred_path = os.path.join(out_dir, f"test_preds_{task.replace('+','_')}_{model}_{mode}.csv")
    df_test.to_csv(pred_path, index=False)

    return out


def main():
    parser = argparse.ArgumentParser(description="Reproduce experiment-report baselines step-by-step.")
    sub = parser.add_subparsers(dest="cmd", required=True)

    # extract
    p_ext = sub.add_parser("extract", help="Extract report recipe (splits/features/params) from 实验结果.zip")
    p_ext.add_argument("--report_zip", required=True, help="Path to 实验结果.zip")
    p_ext.add_argument("--out_dir", required=True, help="Where to write report_recipe.json and unpacked files")

    # run
    p_run = sub.add_parser("run", help="Run reproduction using a recipe (exact) or from scratch (scratch)")
    p_run.add_argument("--clinical_csv", required=True)
    p_run.add_argument("--radiomics_csv", required=True)
    p_run.add_argument("--recipe_json", required=False, default=None, help="Path to report_recipe.json (from extract)")
    p_run.add_argument("--split_json", required=False, default=None, help="Optional custom split json (train_ids/val_ids/test_ids). If provided, overrides recipe split.")
    p_run.add_argument("--task", required=True, choices=["Radiomics", "Clinic", "Clinic+Radiomics", "Fusion", "fusion"])
    p_run.add_argument("--model", required=True, choices=["cph", "coxnet", "gbsa", "all"])
    p_run.add_argument("--mode", required=True, choices=["exact", "scratch"])
    p_run.add_argument("--seed", type=int, default=9)
    p_run.add_argument("--out_dir", required=True)

    # columns
    p_run.add_argument("--clinical_id_col", default="PatientID")
    p_run.add_argument("--radiomics_id_col", default="PatientID")
    p_run.add_argument("--time_col", default="Survival.time")
    p_run.add_argument("--event_col", default="deadstatus.event")

    # scratch feature selection
    p_run.add_argument("--mrmr_ratio", type=float, default=0.01)
    p_run.add_argument("--mrmr_k", type=int, default=None)

    # clinical flags (only meaningful in scratch mode; in exact mode keep them ON to match recipe)
    p_run.add_argument("--use_age", type=int, default=1)
    p_run.add_argument("--use_gender", type=int, default=1)
    p_run.add_argument("--use_histology", type=int, default=1)
    p_run.add_argument("--use_t_stage", type=int, default=1)
    p_run.add_argument("--use_n_stage", type=int, default=1)
    p_run.add_argument("--use_m_stage", type=int, default=1)
    p_run.add_argument("--use_stage", type=int, default=1)
    p_run.add_argument("--age_impute", default="mean", choices=["mean", "median"])

    # eval
    p_run.add_argument("--bootstrap", type=int, default=200)

    args = parser.parse_args()

    if args.cmd == "extract":
        recipe_json = extract_recipe(args.report_zip, args.out_dir)
        print(f"[OK] recipe_json saved to: {recipe_json}")
        return

    # run
    task = args.task
    if task.lower() in ("fusion",):
        task = "Clinic+Radiomics"

    # Build dataset
    clin_raw, rad_raw, time, event = build_xy_from_raw(
        clinical_csv=args.clinical_csv,
        radiomics_csv=args.radiomics_csv,
        clinical_id_col=args.clinical_id_col,
        radiomics_id_col=args.radiomics_id_col,
        time_col=args.time_col,
        event_col=args.event_col,
    )

    clinical_flags = {
        "use_age": int(args.use_age),
        "use_gender": int(args.use_gender),
        "use_histology": int(args.use_histology),
        "use_t_stage": int(args.use_t_stage),
        "use_n_stage": int(args.use_n_stage),
        "use_m_stage": int(args.use_m_stage),
        "use_stage": int(args.use_stage),
    }

    # Recipe
    recipe_entries: List[RecipeEntry] = []
    if args.mode == "exact":
        if not args.recipe_json:
            raise ValueError("EXACT mode requires --recipe_json (from extract).")
        recipe_entries = load_recipe(args.recipe_json)

    models = ["cph", "coxnet", "gbsa"] if args.model == "all" else [args.model]

    results = []
    for m in models:
        if args.mode == "exact":
            ent = pick_recipe_entry(recipe_entries, task=task, model=m)
            train_ids, test_ids = ent.train_ids, ent.test_ids
            selected_features = ent.selected_features
            best_params = ent.best_params
        else:
            # scratch: you must provide split; easiest is still to reuse recipe split
            # If no recipe_json is given, we fall back to a plain 80/20 split with this seed (not recommended for strict reproduction).
            if args.recipe_json:
                recipe_entries = load_recipe(args.recipe_json)
                ent = pick_recipe_entry(recipe_entries, task=task, model="cph")  # any model has the split
                train_ids, test_ids = ent.train_ids, ent.test_ids
            else:
                # fallback random split
                rng = np.random.default_rng(args.seed)
                all_ids = np.array(clin_raw.index.astype(str).tolist())
                rng.shuffle(all_ids)
                n_test = int(round(0.2 * len(all_ids)))
                test_ids = all_ids[:n_test].tolist()
                train_ids = all_ids[n_test:].tolist()
            selected_features = None
            best_params = {}
            # default report-like best params if not provided:
            if m == "cph":
                best_params = {"alpha": 0.8381356590286769, "ties": "efron"}
            elif m == "coxnet":
                best_params = {"l1_ratio": 0.001, "n_alphas": 20}
            elif m == "gbsa":
                best_params = {
                    "criterion": "friedman_mse",
                    "dropout_rate": 0.3,
                    "learning_rate": 0.5710308095913009,
                    "loss": "coxph",
                    "max_depth": 7,
                    "max_features": 0.34046888947419796,
                    "max_leaf_nodes": 12,
                    "min_impurity_decrease": 0.03,
                    "min_samples_leaf": 3,
                    "min_samples_split": 8,
                    "min_weight_fraction_leaf": 0.2,
                    "n_estimators": 100,
                    "subsample": 0.2,
                    "random_state": args.seed,
                }

        # Optional override split
        if args.split_json:
            train_ids, test_ids = load_split_json(args.split_json)

        out = run_one(
            task=task,
            model=m,
            clin_raw=clin_raw,
            rad_raw=rad_raw,
            time=time,
            event=event,
            train_ids=train_ids,
            test_ids=test_ids,
            selected_features=selected_features,
            best_params=best_params,
            seed=args.seed,
            mode=args.mode,
            mrmr_ratio=args.mrmr_ratio,
            mrmr_k=args.mrmr_k,
            bootstrap=args.bootstrap,
            out_dir=args.out_dir,
            clinical_flags=clinical_flags,
            age_impute=args.age_impute,
        )
        results.append(out)

        print("\n" + "-"*72)
        print(f"[{task} | {m} | {args.mode}]")
        print(f"n_train={out['n_train']} n_test={out['n_test']} n_features={out['n_features']}")
        print(f"train_cindex={out['train_cindex']:.4f}  test_cindex={out['test_cindex']:.4f}")
        print(f"boot_mean±std = {out['boot_mean']:.4f} ± {out['boot_std']:.4f}")
        print(f"CI(norm) 95% = [{out['ci_norm_2.5']:.4f}, {out['ci_norm_97.5']:.4f}]")
        print(f"CI(pct)  95% = [{out['ci_pct_2.5']:.4f}, {out['ci_pct_97.5']:.4f}]")
        if m == "coxnet":
            print(f"coxnet best_alpha={out['model_params'].get('best_alpha', None)} best_cv={out['model_params'].get('best_cv_cindex', None)}")

    # save summary
    sum_path = os.path.join(args.out_dir, "summary.json")
    with open(sum_path, "w", encoding="utf-8") as f:
        json.dump(results, f, ensure_ascii=False, indent=2)
    print(f"\n[OK] Saved summary: {sum_path}")


if __name__ == "__main__":
    main()