#!/usr/bin/env python
"""Phase 4: External Test on NSCLC-Radiogenomics (RG)

What this script does
---------------------
1) Reconstruct the exact LUNG1 CV folds used in phase3_0617.py
2) For each fold checkpoint (fold_0..fold_4/best.pt):
   - Re-fit the *same* clinical feature preprocessing using that fold's LUNG1-train split
     (age StandardScaler, mode-imputation for T/N/M/overall_stage, missing indicators)
   - Run inference on RG Phase2 outputs (CT+EDT already in [0,1])
   - Compute Harrell C-index and Uno IPCW C-index on RG
3) Optionally build an ensemble over the fold models (z-scored risk average)

Assumptions (match your pipeline)
---------------------------------
- RG Phase2 outputs were generated by your window+EDT pipeline (HU window [-1000,400] -> [0,1]).
- Each RG record has out_ct and out_edt (NIfTI) and a patient_id.
- You have LUNG1 crop_log.csv + clinical.csv that were used for training those checkpoints.

Usage example
-------------
python phase4_external_test_radiogenomics.py \
  --lung1_crop_log   /home/lichengze/Research/CNN_pipeline/phase2_outputs/crop_log.csv \
  --lung1_clinical   /home/lichengze/Research/CNN_pipeline/NSCLC-Radiomics-Lung1.clinical.csv \
  --ckpt_root        /home/lichengze/Research/CNN_pipeline/phase3_outputs/learning_rate/learning_rate_corrected/output/lr_7e-4 \
  --rg_crop_log      /home/lichengze/Research/Radiogenomics/phase2_outputs/phase2_crop_log.csv \
  --rg_clinical      /home/lichengze/Research/Radiogenomics/Radiogenomics_clinical_aligned.csv \
  --out_dir          /home/lichengze/Research/Radiogenomics/external_test_lr7e-4

Notes
-----
- Default is to evaluate ONLY cases with has_segmentation==True (recommended for your CT+EDT model).
- If you want to include no-seg cases (center crop + EDT=0), pass --include_no_seg.
"""

from __future__ import annotations

import os
import re
import json
import math
import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple, Optional

import numpy as np
import pandas as pd

import torch
import torch.nn as nn

from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler

from monai.transforms import (
    Compose,
    LoadImaged,
    EnsureChannelFirstd,
    EnsureTyped,
    ConcatItemsd,
    DeleteItemsd,
    ToTensord,
    Lambdad,
)
from monai.networks.nets import resnet as monai_resnet

from sksurv.metrics import concordance_index_censored, concordance_index_ipcw


# ----------------------------
# Repro
# ----------------------------

def set_seed(seed: int = 42):
    import random
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = False
    torch.backends.cudnn.benchmark = True


def to_structured_y(times: np.ndarray, events: np.ndarray):
    """Convert (time, event) -> sksurv structured array."""
    return np.array(
        [(bool(e), float(t)) for t, e in zip(times, events)],
        dtype=[("event", bool), ("time", float)],
    )


# ----------------------------
# Clinical feature engineering (must match phase3_0617.py)
# ----------------------------

from collections import Counter


def _safe_mode(values: np.ndarray, default: float) -> float:
    vals = values[~np.isnan(values)]
    if vals.size == 0:
        return float(default)
    cnt = Counter(vals.tolist())
    mode_val = sorted(cnt.items(), key=lambda x: (-x[1], x[0]))[0][0]
    return float(mode_val)


def _parse_T(series: pd.Series) -> np.ndarray:
    out = []
    for v in series:
        if pd.isna(v):
            out.append(np.nan)
            continue
        s = str(v).upper()
        m = re.search(r"(\d)", s)
        if m:
            t = float(m.group(1))
            if 1.0 <= t <= 4.0:
                out.append(t)
            else:
                out.append(np.nan)
        else:
            out.append(np.nan)
    return np.array(out, dtype=np.float32)


def _parse_N(series: pd.Series) -> np.ndarray:
    out = []
    for v in series:
        if pd.isna(v):
            out.append(np.nan)
            continue
        s = str(v).upper()
        m = re.search(r"(\d)", s)
        if m:
            n = float(m.group(1))
            if 0.0 <= n <= 3.0:
                out.append(n)
            else:
                out.append(np.nan)
        else:
            out.append(np.nan)
    return np.array(out, dtype=np.float32)


def _parse_M(series: pd.Series) -> Tuple[np.ndarray, np.ndarray]:
    """Return (M01, M_misc) as in phase3_0617.py."""
    M01, M_misc = [], []
    for v in series:
        if pd.isna(v):
            M01.append(np.nan)
            M_misc.append(0.0)
            continue
        s = str(v).upper()
        m = re.search(r"(\d)", s)
        if not m:
            M01.append(np.nan)
            M_misc.append(0.0)
            continue
        mv = int(m.group(1))
        if mv == 0:
            M01.append(0.0)
            M_misc.append(0.0)
        elif mv == 1:
            M01.append(1.0)
            M_misc.append(0.0)
        else:
            # unexpected values (e.g. M2)
            M01.append(1.0)
            M_misc.append(1.0)
    return np.array(M01, dtype=np.float32), np.array(M_misc, dtype=np.float32)


def _map_overall(series: pd.Series) -> np.ndarray:
    mapping = {
        "I": 0.2,
        "1": 0.2,
        "II": 0.4,
        "2": 0.4,
        "IIIA": 0.6,
        "3A": 0.6,
        "IIIB": 0.8,
        "3B": 0.8,
        "IV": 1.0,
        "4": 1.0,
    }
    out = []
    for v in series:
        if pd.isna(v):
            out.append(np.nan)
            continue
        s = str(v).strip().upper().replace("STAGE", "").replace(" ", "")
        # unicode roman numerals
        s = (
            s.replace("ⅢA", "IIIA")
            .replace("ⅢB", "IIIB")
            .replace("Ⅱ", "II")
            .replace("Ⅳ", "IV")
            .replace("Ⅰ", "I")
        )
        if s in mapping:
            out.append(mapping[s])
        elif s in ["III"]:
            out.append(0.7)
        else:
            out.append(np.nan)
    return np.array(out, dtype=np.float32)


@dataclass
class ClinicalParams:
    # age
    age_train_median: float
    age_scaler_mean: float
    age_scaler_scale: float

    # T/N/M/overall imputation
    T_mode: float
    N_mode: float
    M_mode: float
    overall_mode: float


FEATURE_NAMES_12 = [
    "age_scaled",
    "age_missing",
    "gender_male",
    "T_norm",
    "T_missing",
    "N_norm",
    "N_missing",
    "M01",
    "M_missing",
    "M_misc",
    "overall_stage_ord",
    "overall_missing",
]


def fit_clinical_params(train_df: pd.DataFrame) -> ClinicalParams:
    """Fit fold-specific clinical preprocessing on LUNG1-train split."""
    # age
    age_raw = pd.to_numeric(train_df.get("age", pd.Series([np.nan] * len(train_df))), errors="coerce").values.astype(
        np.float32
    )
    age_train_median = float(np.nanmedian(age_raw)) if np.any(~np.isnan(age_raw)) else 0.0

    # StandardScaler fit on age_filled of train split
    age_filled = age_raw.copy()
    age_filled[np.isnan(age_filled)] = age_train_median
    scaler = StandardScaler()
    scaler.fit(age_filled.reshape(-1, 1))

    # T/N/M/overall
    T_num = _parse_T(train_df.get("T", pd.Series([np.nan] * len(train_df))))
    N_num = _parse_N(train_df.get("N", pd.Series([np.nan] * len(train_df))))
    M01, _ = _parse_M(train_df.get("M", pd.Series([np.nan] * len(train_df))))
    ov = _map_overall(train_df.get("overall_stage", pd.Series([np.nan] * len(train_df))))

    return ClinicalParams(
        age_train_median=age_train_median,
        age_scaler_mean=float(scaler.mean_[0]),
        age_scaler_scale=float(scaler.scale_[0] if scaler.scale_[0] > 1e-12 else 1.0),
        T_mode=_safe_mode(T_num, default=2.0),
        N_mode=_safe_mode(N_num, default=1.0),
        M_mode=_safe_mode(M01, default=0.0),
        overall_mode=_safe_mode(ov, default=0.6),
    )


def transform_clinical(df: pd.DataFrame, params: ClinicalParams) -> np.ndarray:
    """Transform ANY dataset (RG or LUNG1) to the 12-dim clinical vector."""
    n = len(df)

    # age
    age_raw = pd.to_numeric(df.get("age", pd.Series([np.nan] * n)), errors="coerce").values.astype(np.float32)
    age_missing = np.isnan(age_raw).astype(np.float32)
    age_filled = age_raw.copy()
    age_filled[np.isnan(age_filled)] = params.age_train_median
    age_scaled = ((age_filled - params.age_scaler_mean) / params.age_scaler_scale).astype(np.float32)

    # gender
    gender_ser = df.get("gender", pd.Series([""] * n)).astype(str).str.upper().str[0]
    gender_male = (gender_ser == "M").astype(np.float32).values

    # T
    T_num = _parse_T(df.get("T", pd.Series([np.nan] * n)))
    T_missing = np.isnan(T_num).astype(np.float32)
    T_filled = T_num.copy()
    T_filled[np.isnan(T_filled)] = params.T_mode
    T_norm = ((T_filled - 1.0) / 3.0).astype(np.float32)

    # N
    N_num = _parse_N(df.get("N", pd.Series([np.nan] * n)))
    N_missing = np.isnan(N_num).astype(np.float32)
    N_filled = N_num.copy()
    N_filled[np.isnan(N_filled)] = params.N_mode
    N_norm = ((N_filled - 0.0) / 3.0).astype(np.float32)

    # M
    M01, M_misc = _parse_M(df.get("M", pd.Series([np.nan] * n)))
    M_missing = np.isnan(M01).astype(np.float32)
    M01_filled = M01.copy()
    M01_filled[np.isnan(M01_filled)] = params.M_mode

    # overall stage
    ov = _map_overall(df.get("overall_stage", pd.Series([np.nan] * n)))
    overall_missing = np.isnan(ov).astype(np.float32)
    ov_filled = ov.copy()
    ov_filled[np.isnan(ov_filled)] = params.overall_mode

    X = np.stack(
        [
            age_scaled,
            age_missing,
            gender_male,
            T_norm,
            T_missing,
            N_norm,
            N_missing,
            M01_filled,
            M_missing,
            M_misc,
            ov_filled,
            overall_missing,
        ],
        axis=1,
    ).astype(np.float32)

    # safety
    X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)
    return X


# ----------------------------
# Model (same as phase3_0617.py)
# ----------------------------

class ResNet10_Clinical_GN(nn.Module):
    def __init__(self, in_channels: int = 2, clinical_dim: int = 12, n_bins: int = 14, dropout: float = 0.35):
        super().__init__()

        self.backbone = monai_resnet.resnet10(
            spatial_dims=3,
            n_input_channels=in_channels,
            num_classes=512,
        )
        self._replace_bn_with_gn(self.backbone)

        self.clinical_encoder = nn.Sequential(
            nn.Linear(clinical_dim, 32),
            nn.LayerNorm(32),
            nn.ReLU(inplace=True),
            nn.Dropout(dropout * 0.5),
            nn.Linear(32, 64),
            nn.LayerNorm(64),
            nn.ReLU(inplace=True),
        )

        self.head = nn.Sequential(
            nn.Linear(512 + 64, 256),
            nn.LayerNorm(256),
            nn.ReLU(inplace=True),
            nn.Dropout(dropout),
            nn.Linear(256, 128),
            nn.LayerNorm(128),
            nn.ReLU(inplace=True),
            nn.Dropout(dropout),
            nn.Linear(128, n_bins),
        )

    def _replace_bn_with_gn(self, module, num_groups: int = 8):
        for name, child in module.named_children():
            if isinstance(child, (nn.BatchNorm1d, nn.BatchNorm2d, nn.BatchNorm3d)):
                num_channels = child.num_features
                groups = min(num_groups, num_channels)
                while num_channels % groups != 0:
                    groups = groups // 2
                    if groups == 0:
                        groups = 1
                        break
                setattr(module, name, nn.GroupNorm(groups, num_channels))
            else:
                self._replace_bn_with_gn(child, num_groups)

    def forward(self, x_img, x_clinical):
        f_img = self.backbone(x_img)
        f_clin = self.clinical_encoder(x_clinical)
        f = torch.cat([f_img, f_clin], dim=1)
        return self.head(f)


# ----------------------------
# MONAI transforms & dataset
# ----------------------------


def build_infer_transforms() -> Compose:
    """Match phase3_0617.py inference preprocessing: CT/EDT already [0,1], just clamp."""
    return Compose(
        [
            LoadImaged(keys=["ct", "edt"]),
            EnsureChannelFirstd(keys=["ct", "edt"]),
            EnsureTyped(keys=["ct", "edt"], dtype=torch.float32, track_meta=False),
            Lambdad(keys=["ct", "edt"], func=lambda x: torch.nan_to_num(x, 0.0, 0.0, 0.0)),
            Lambdad(keys=["ct", "edt"], func=lambda x: torch.clamp(x, 0.0, 1.0)),
            ConcatItemsd(keys=["ct", "edt"], name="image"),
            DeleteItemsd(keys=["ct", "edt"]),
            ToTensord(keys=["image"]),
        ]
    )


class InferDataset(Dataset):
    def __init__(self, records: List[dict], clinical: np.ndarray, transform: Compose):
        self.records = records
        self.clinical = clinical
        self.transform = transform

    def __len__(self):
        return len(self.records)

    def __getitem__(self, idx: int):
        rec = dict(self.records[idx])
        data = self.transform(rec)
        data["clinical"] = torch.tensor(self.clinical[idx], dtype=torch.float32)
        # keep patient_id for logging
        data["patient_id"] = rec.get("patient_id", "NA")
        return data


# ----------------------------
# Prediction (4-view flip TTA)
# ----------------------------


def survival_from_logits(logits: torch.Tensor, n_time_bins: int) -> torch.Tensor:
    haz = torch.sigmoid(logits[:, :n_time_bins])
    surv = torch.cumprod(1.0 - haz, dim=1)
    return surv


@torch.no_grad()
def predict_survival_tta4(
    model: nn.Module,
    img_batch: torch.Tensor,
    clin_batch: torch.Tensor,
    device: torch.device,
    n_time_bins: int,
    use_tta: bool = True,
) -> np.ndarray:
    """4-view TTA (H/W flips) matching phase3_0617.py."""
    model.eval()

    img_batch = img_batch.to(device)
    clin_batch = clin_batch.to(device)

    if not use_tta:
        logits = model(img_batch, clin_batch)
        surv = survival_from_logits(logits, n_time_bins)
        return surv.cpu().numpy()

    views = [
        img_batch,
        torch.flip(img_batch, dims=[-2]),
        torch.flip(img_batch, dims=[-1]),
        torch.flip(img_batch, dims=[-2, -1]),
    ]

    outs = []
    for v in views:
        logits = model(v, clin_batch)
        outs.append(survival_from_logits(logits, n_time_bins))

    return torch.stack(outs, dim=0).mean(dim=0).cpu().numpy()


# ----------------------------
# Data loading helpers (match phase3_0617.py naming heuristics)
# ----------------------------


def standardize_clinical_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Rename columns to match the training script's expectations."""
    col_map = {}
    for col in df.columns:
        col_clean = col.lower().strip()

        if "patient" in col_clean or "case" in col_clean or col_clean in ["id", "case id", "case_id"]:
            col_map[col] = "patient_id"
        elif ("survival" in col_clean and "time" in col_clean) or col_clean in ["time", "time_days", "os", "os_days"]:
            col_map[col] = "time"
        elif "dead" in col_clean or "event" in col_clean or col_clean in ["status", "survival_status"]:
            col_map[col] = "event"
        elif "overall" in col_clean and "stage" in col_clean:
            col_map[col] = "overall_stage"
        elif (".t." in col_clean or col_clean.startswith("t") or col_clean.startswith("clinical.t")) and "stage" in col_clean:
            col_map[col] = "T"
        elif (".n." in col_clean or col_clean.startswith("n") or col_clean.startswith("clinical.n")) and "stage" in col_clean:
            col_map[col] = "N"
        elif (".m." in col_clean or col_clean.startswith("m") or col_clean.startswith("clinical.m")) and "stage" in col_clean:
            col_map[col] = "M"
        elif "age" in col_clean and "stage" not in col_clean:
            col_map[col] = "age"
        elif "gender" in col_clean or "sex" in col_clean:
            col_map[col] = "gender"

    return df.rename(columns=col_map)


def load_manifest(crop_log_csv: str, clinical_csv: str, require_edt: bool = True) -> pd.DataFrame:
    crop = pd.read_csv(crop_log_csv)
    clin = pd.read_csv(clinical_csv)
    clin = standardize_clinical_columns(clin)

    # Crop log columns vary slightly between runs; handle both.
    # Expect: patient_id, out_ct, out_edt; (out_mask optional), has_segmentation optional
    needed = ["patient_id", "out_ct"]
    if require_edt:
        needed.append("out_edt")
    for c in needed:
        if c not in crop.columns:
            raise ValueError(f"{crop_log_csv} missing required column: {c}")

    cols = ["patient_id", "out_ct"] + (["out_edt"] if "out_edt" in crop.columns else [])
    if "out_mask" in crop.columns:
        cols.append("out_mask")
    if "has_segmentation" in crop.columns:
        cols.append("has_segmentation")

    crop2 = crop[cols].copy()
    crop2 = crop2.rename(columns={"out_ct": "ct_path", "out_edt": "edt_path", "out_mask": "mask_path"})

    # Merge
    m = crop2.merge(clin, on="patient_id", how="inner")

    # Must have survival labels
    if "time" not in m.columns or "event" not in m.columns:
        raise ValueError(
            f"After merging, manifest lacks time/event columns. Got columns: {list(m.columns)[:30]}"
        )

    m = m.dropna(subset=["time", "event"]).copy()
    m["time"] = pd.to_numeric(m["time"], errors="coerce").astype(float)
    m["event"] = pd.to_numeric(m["event"], errors="coerce").astype(float)
    m = m.dropna(subset=["time", "event"]).copy()
    m["time"] = m["time"].astype(int)
    m["event"] = m["event"].astype(int)

    # default has_segmentation if missing
    if "has_segmentation" not in m.columns:
        m["has_segmentation"] = True

    return m


# ----------------------------
# Metrics helpers
# ----------------------------


def safe_tau_from_train(train_times: np.ndarray, train_events: np.ndarray, test_times: np.ndarray) -> float:
    evt_times = train_times[train_events == 1]
    if evt_times.size == 0:
        # no events in train: fall back to max test time
        return float(np.max(test_times))
    tau = float(np.quantile(evt_times, 0.9))
    # IPCW requires tau <= max(test_times)
    tau = min(tau, float(np.max(test_times) - 1e-3))
    # also guard against non-positive
    tau = max(tau, 1.0)
    return tau


def compute_cindices(
    y_train_struct,
    y_test_struct,
    risk: np.ndarray,
    tau: float,
) -> Dict[str, float]:
    out = {}
    # Harrell
    out["harrell"] = float(
        concordance_index_censored(y_test_struct["event"], y_test_struct["time"], risk)[0]
    )
    # Uno
    out["uno"] = float(concordance_index_ipcw(y_train_struct, y_test_struct, risk, tau=tau)[0])
    return out


# ----------------------------
# Main
# ----------------------------


def main():
    parser = argparse.ArgumentParser(
        description="External test: LUNG1-trained ResNet10+clinical on NSCLC-Radiogenomics",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    parser.add_argument("--lung1_crop_log", type=str, required=True)
    parser.add_argument("--lung1_clinical", type=str, required=True)
    parser.add_argument("--ckpt_root", type=str, required=True, help="Folder containing fold_0..fold_4")

    parser.add_argument("--rg_crop_log", type=str, required=True)
    parser.add_argument("--rg_clinical", type=str, required=True)

    parser.add_argument("--out_dir", type=str, required=True)

    parser.add_argument("--n_folds", type=int, default=5)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--batch_size", type=int, default=2)
    parser.add_argument("--num_workers", type=int, default=4)

    parser.add_argument(
        "--include_no_seg",
        action="store_true",
        help="Include RG cases without segmentations (center crop + EDT=0). Not recommended for primary external validation.",
    )

    parser.add_argument(
        "--no_tta",
        action="store_true",
        help="Disable 4-view flip TTA at inference (overrides checkpoint).",
    )

    parser.add_argument("--device", type=str, default="cuda", help="cuda or cpu")

    args = parser.parse_args()

    set_seed(args.seed)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # 1) Load manifests
    lung1 = load_manifest(args.lung1_crop_log, args.lung1_clinical, require_edt=True)
    rg = load_manifest(args.rg_crop_log, args.rg_clinical, require_edt=True)

    if not args.include_no_seg:
        rg = rg[rg["has_segmentation"] == True].copy()

    rg = rg.reset_index(drop=True)

    print("\n" + "=" * 80)
    print("External Test Setup")
    print("=" * 80)
    print(f"LUNG1: n={len(lung1)} | events={lung1['event'].sum()} ({lung1['event'].mean()*100:.1f}%)")
    print(f"RG:    n={len(rg)} | events={rg['event'].sum()} ({rg['event'].mean()*100:.1f}%)")
    if not args.include_no_seg:
        print("RG subset: has_segmentation==True")
    else:
        print("RG subset: ALL (including no-seg center-crop cases)")
    print("=" * 80)

    # 2) Rebuild LUNG1 folds (must match phase3_0617.py)
    skf = StratifiedKFold(n_splits=args.n_folds, shuffle=True, random_state=args.seed)
    folds = list(skf.split(np.zeros(len(lung1)), lung1["event"].values))

    device = torch.device(args.device if (args.device == "cpu" or torch.cuda.is_available()) else "cpu")
    print(f"Device: {device}")

    # 3) RG dataloader records (paths)
    records_rg = [
        {"ct": rg.loc[i, "ct_path"], "edt": rg.loc[i, "edt_path"], "patient_id": rg.loc[i, "patient_id"]}
        for i in range(len(rg))
    ]

    tfm = build_infer_transforms()

    # Collect per-fold risks
    fold_metrics = []
    fold_risks = []

    # RG labels
    rg_times = rg["time"].values.astype(float)
    rg_events = rg["event"].values.astype(int)
    y_rg = to_structured_y(rg_times, rg_events)

    for fold_id, (idx_train, idx_val) in enumerate(folds):
        ckpt_path = Path(args.ckpt_root) / f"fold_{fold_id}" / "best.pt"
        if not ckpt_path.exists():
            raise FileNotFoundError(f"Missing checkpoint: {ckpt_path}")

        ckpt = torch.load(str(ckpt_path), map_location="cpu", weights_only=False)
        cuts = np.array(ckpt["cuts"], dtype=float)
        n_time_bins = int(ckpt.get("n_time_bins", len(cuts) - 1))
        use_tta_ckpt = bool(ckpt.get("use_tta", True))
        use_tta = (not args.no_tta) and use_tta_ckpt

        # Fit clinical preprocessing on THIS fold's LUNG1-train split
        lung1_train_df = lung1.iloc[idx_train].copy()
        clin_params = fit_clinical_params(lung1_train_df)

        # Transform RG clinical to 12-dim features  
        X_rg = transform_clinical(rg, clin_params)
        use_clinical = bool(ckpt.get("use_clinical", True))
        if not use_clinical:
            X_rg = np.zeros_like(X_rg, dtype=np.float32)

        ds = InferDataset(records_rg, X_rg, tfm)
        dl = DataLoader(
            ds,
            batch_size=args.batch_size,
            shuffle=False,
            num_workers=args.num_workers,
            pin_memory=(device.type == "cuda"),
            persistent_workers=(args.num_workers > 0),
        )

        # Build model & load
        model = ResNet10_Clinical_GN(in_channels=2, clinical_dim=X_rg.shape[1], n_bins=n_time_bins, dropout=0.35)
        model.load_state_dict(ckpt["state_dict"], strict=True)
        model.to(device)

        # Inference
        all_surv = []
        for batch in dl:
            surv = predict_survival_tta4(
                model,
                batch["image"],
                batch["clinical"],
                device=device,
                n_time_bins=n_time_bins,
                use_tta=use_tta,
            )
            all_surv.append(surv)

        surv = np.concatenate(all_surv, axis=0)  # (N, T)

        # Risk definitions (same as phase3_0617.py)
        bin_mids = (cuts[:-1] + cuts[1:]) / 2.0
        # integral risk
        risk_integral = -np.trapz(surv, x=bin_mids, axis=1)
        # 24m risk (optional)
        t24 = 730.0
        t_idx_24m = int(np.argmin(np.abs(bin_mids - t24)))
        surv_24m = surv[:, t_idx_24m] if t_idx_24m < surv.shape[1] else surv[:, -1]
        risk_24m = 1.0 - surv_24m

        # Metrics
        y_train_struct = to_structured_y(lung1.iloc[idx_train]["time"].values.astype(float), lung1.iloc[idx_train]["event"].values.astype(int))
        tau = safe_tau_from_train(
            lung1.iloc[idx_train]["time"].values.astype(float),
            lung1.iloc[idx_train]["event"].values.astype(int),
            rg_times,
        )

        m = compute_cindices(y_train_struct, y_rg, risk_integral, tau=tau)

        print(
            f"Fold {fold_id}: RG Uno={m['uno']:.3f} | Harrell={m['harrell']:.3f} | "
            f"TTA={'ON' if use_tta else 'OFF'} | tau={tau:.1f}"
        )

        fold_metrics.append(
            {
                "fold": fold_id,
                "uno": m["uno"],
                "harrell": m["harrell"],
                "tau": tau,
                "use_tta": use_tta,
                "ckpt": str(ckpt_path),
            }
        )
        fold_risks.append(risk_integral)

        # Save per-fold predictions
        fold_out = out_dir / f"fold_{fold_id}"
        fold_out.mkdir(parents=True, exist_ok=True)
        pd.DataFrame(
            {
                "patient_id": rg["patient_id"].values,
                "time": rg_times,
                "event": rg_events,
                "risk_integral": risk_integral,
                "risk_24m": risk_24m,
                "surv_24m": surv_24m,
            }
        ).to_csv(fold_out / "rg_pred.csv", index=False)

    # 4) Ensemble across folds
    risks = np.stack(fold_risks, axis=0)  # (K, N)

    # z-score each fold then average (keeps ordering stable across fold-specific time bins)
    risks_z = (risks - risks.mean(axis=1, keepdims=True)) / (risks.std(axis=1, keepdims=True) + 1e-8)
    risk_ens = risks_z.mean(axis=0)

    # Uno uses censoring from FULL LUNG1 here (reasonable for the ensemble report)
    y_lung1_full = to_structured_y(lung1["time"].values.astype(float), lung1["event"].values.astype(int))
    tau_full = safe_tau_from_train(lung1["time"].values.astype(float), lung1["event"].values.astype(int), rg_times)

    ens_metrics = compute_cindices(y_lung1_full, y_rg, risk_ens, tau=tau_full)

    print("\n" + "=" * 80)
    print(f"Ensemble (z-avg over {args.n_folds} fold models)")
    print(f"RG Uno={ens_metrics['uno']:.3f} | Harrell={ens_metrics['harrell']:.3f} | tau={tau_full:.1f}")
    print("=" * 80)

    # Save summary
    summary = {
        "lung1": {
            "n": int(len(lung1)),
            "events": int(lung1["event"].sum()),
            "event_rate": float(lung1["event"].mean()),
        },
        "radiogenomics": {
            "n": int(len(rg)),
            "events": int(rg["event"].sum()),
            "event_rate": float(rg["event"].mean()),
            "include_no_seg": bool(args.include_no_seg),
        },
        "per_fold": fold_metrics,
        "ensemble": {
            **ens_metrics,
            "tau": float(tau_full),
            "method": "zscore_avg_risk_integral",
        },
    }

    with open(out_dir / "external_test_summary.json", "w") as f:
        json.dump(summary, f, indent=2)

    pd.DataFrame(fold_metrics).to_csv(out_dir / "external_test_per_fold.csv", index=False)

    pd.DataFrame(
        {
            "patient_id": rg["patient_id"].values,
            "time": rg_times,
            "event": rg_events,
            "risk_ensemble": risk_ens,
        }
    ).to_csv(out_dir / "rg_pred_ensemble.csv", index=False)

    print(f"\nSaved to: {out_dir}")


if __name__ == "__main__":
    main()
